
name: "Github workflow"
on:
  push:
    branches: "main"
  pull_request:
    branches: "*"
  workflow_dispatch:
jobs:
  lint:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2

      - name: Setup Python
        uses: actions/setup-python@v1
        with:
          python-version: "3.10"

      - name: Setup Invoke
        run: pip install invoke

      - name: Install Requirements
        run: inv build


