name: "Run GB report"
on:
  push:
    branches: "main"
  pull_request:
    branches: "*"
  workflow_dispatch:
jobs:
  build-image:
    runs-on: ubuntu-latest
    env:
      UV_SYSTEM_PYTHON: true
    steps:
      - uses: actions/checkout@v4

      - name: Setup Python
        uses: actions/setup-python@v4
        with:
            python-version: "3.10"

      - name: Setup environment
        run: |
          python -m venv venv

      - name: Install dependencies
        run: |
          source venv/bin/activate
          pip install uv invoke pip-tools pylint pytest
          invoke build
          pip install .
          
      - name: Save Python environment
        run: |
          tar -czf python-env.tar.gz venv

      - name: Upload as artefact
        uses: actions/upload-artifact@v3
        with:
          name: python-env
          path: python-env.tar.gz

  run-gb-report:
    runs-on: ubuntu-latest
    needs: build-image
    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Download python environment
        uses: actions/download-artifact@v3
        with:
          name: python-env
          path: .

      - name: Extract Python environment
        run: |
          tar -xzf python-env.tar.gz

      - name: Run report
        run: |
          source venv/bin/activate
          run_gb_uwh_report
        env:
          STRAVA_CLIENT_ID='${{ secrets.STRAVA_CLIENT_ID }}'
          STRAVA_CLIENT_SECRET='${{ secrets.STRAVA_CLIENT_SECRET }}'
          MAILGUN_API_KEY='${{ secrets.MAILGUN_API_KEY }}'
          MAILGUN_API_URL='${{ secrets.MAILGUN_API_URL }}'
          MAILGUN_SENDER_ADDRESS= '${{ secrets.MAILGUN_SENDER_ADDRESS }}'

  cleanup:
    runs-on: ubuntu-latest
    needs: run-gb-report
    if: always()
    steps:
      - uses: geekyeggo/delete-artifact@v1
        with:
          name: python-env
