name: "Install package"
on:
  push:
    branches: "main"
  pull_request:
    branches: "*"
  workflow_dispatch:
jobs:
  build-image:
    runs-on: ubuntu-latest
    env:
      UV_SYSTEM_PYTHON: true
    steps:
      - uses: actions/checkout@v4

      - name: Setup Python
        uses: actions/setup-python@v4
        with:
            python-version: "3.10"

      - name: Setup environment
        run: |
          python -m venv venv

      - name: Install dependencies
        run: |
          source venv/bin/activate
          pip install uv invoke pip-tools pylint pytest
          invoke build
          pip install .
          
      - name: Save Python environment
        run: |
          tar -czf python-env.tar.gz venv

      - name: Upload as artefact
        uses: actions/upload-artifact@v4
        with:
          name: python-env
          path: python-env.tar.gz

  cleanup:
    runs-on: ubuntu-latest
    needs: build-image
    if: always()
    steps:
      - uses: geekyeggo/delete-artifact@v5
        with:
          name: python-env
